### PR TITLE
[WIP] Update currency list

### LINKED ISSUE #2: Planned currencies
Do you think it is possible to somehow add planned currencies to the list?

Reference: https://github.com/moneyphp/money/pull/193

### PR DESCRIPTION
**Pull request by umpirsky**
Attempt to fix https://github.com/umpirsky/currency-list/issues/2.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Hm, it is relatively hard to review the changes, don't you think? :stuck_out_tongue:

**Comment by umpirsky** [comment]
@sagikazarmark Yes, because GitHub sucks. :)

**Comment by sagikazarmark** [comment]
Did you miss adding the "@" before "GitHub"? :stuck_out_tongue_winking_eye:

**Comment by umpirsky** [comment]
hehehe-hehehehe-9MFsKQ8A6HCN2

**Comment by umpirsky** [comment]
Closing in favor of https://github.com/umpirsky/currency-list/pull/7.

**Pull request closed without merging**
